#!/bin/bash

# Check active connections
nmcli connection show --active | tail -n +2 | grep -v docker | grep -v br >> /dev/null
if [[ $? -eq 0 ]]; then
    echo "[wifi-connect] there is an active connection, skipping"
    exit 0
fi
    
# Check if the wlan0 interface exists
if [[ -f /sys/class/net/wlan0 ]]; then
    echo "[wifi-connect] wlan0 interface does not exist"
    exit 1
fi

# Custom SSID & PASS
IFACE=${IFACE:-"eth0"}
MAC=$(cat /sys/class/net/$IFACE/address | sed 's/://g' | tail -c 5)
SSID=${SSID:-"RAK_${MAC^^}"}
PASS=${PASS:-"rakwireless"}

# Start service
echo "[wifi-connect] starting WiFi Connect (SSID: $SSID)"
wifi-connect --portal-ssid $SSID --portal-passphrase $PASS --portal-gateway 192.168.230.1 --portal-dhcp-range 192.168.230.2,192.168.230.254

exit 0
