#!/bin/bash

# Get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')

# Get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})

# Get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`

# Get processors
PROCESSOR_NAME=`grep "Model" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
if [[ "$PROCESSOR_NAME" == "" ]]; then
    PROCESSOR_NAME=`grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
fi
PROCESSOR_COUNT=`grep -ioP 'processor\t:' /proc/cpuinfo | wc -l`

# Get CPU temperature
TEMPERATURE=`vcgencmd measure_temp 2> /dev/null | sed 's/temp=//'`

# Get IP addresses
SHOW_IP_PATTERN="^bond.*|^[ewr].*|^br.*|^lt.*|^umts.*|^lan.*"
ips=()
docker_br_intf=`docker network ls -f driver=bridge --format "br-{{.ID}}"`  #docker bridge network interface
for f in /sys/class/net/*; do
    intf=$(basename $f)
    # match only interface names starting with e (Ethernet), br (bridge), w (wireless), r (some Ralink drivers use>
    # and get rid of bridge interface created by docker
    if ([[ $intf =~ $SHOW_IP_PATTERN ]] && !([[ $docker_br_intf =~ $intf ]])) then
        tmp=$(ip -4 addr show dev $intf | awk '/inet/ {print $2}' | cut -d'/' -f1)
        # add both name and IP - can be informative but becomes ugly with long persistent/predictable device names
        #[[ -n $tmp ]] && ips+=("$intf: $tmp")
        # add IP only
        [[ -n $tmp ]] && ips+=("$tmp")
    fi 
done
IP=$( echo ${ips[@]} )

W="\e[0;39m"
G="\e[1;32m"

echo -e "
${W}system info:
$W  Distro......: $W`cat /etc/os-release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'`
$W  Kernel......: $W`uname -sr`

$W  Uptime......: $W`uptime -p`
$W  Load........: $G$LOAD1$W (1m), $G$LOAD5$W (5m), $G$LOAD15$W (15m)
$W  Processes...: $W$G$PROCESS_ROOT$W (root), $G$PROCESS_USER$W (user), $G$PROCESS_ALL$W (total)

$W  CPU.........: $W$PROCESSOR_NAME ($G$PROCESSOR_COUNT$W vCPU)
$W  Memory......: $G$USED$W used, $G$AVAIL$W avail, $G$TOTAL$W total$W
$W  CPU temp....: $G$TEMPERATURE$W

$W  IP..........: $G$IP$W
"
