version: '2.0'

services:

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host      # required to read main interface MAC instead of virtual one
    environment:
      MODEL: "RAK2287"
      INTERFACE: "SPI"
      TC_KEY: "..."         # Copy here your API key from the LNS
